version: '3'
services:
  ng1:
    image: nginx:latest
    container_name: ng1
    ports:
      - "9090:80"  # Expose port 9090 on the host to port 80 in the container
    volumes:
      - ./vol:/usr/share/nginx/html  # Mount the 'vol' folder into the container's HTML directory

  ng2:
    image: nginx:latest
    container_name: ng2
    ports:
      - "8080:80"  
    volumes:
      - ./vol:/usr/share/nginx/html  
